CRICKET_WORDS = [

    ("IPL", "PSL"),
    ("World Cup", "Champions Trophy"),
    ("Test Cricket", "ODI Cricket"),
    ("Powerplay", "Super Over"),
    ("Yorker", "Bouncer"),
    ("Googly", "Doosra"),
    ("Cover Drive", "Straight Drive"),
    ("Hat-trick", "Five Wicket Haul"),
    ("Orange Cap", "Purple Cap"),
    ("Third Umpire", "DRS"),
    ("Free Hit", "No Ball"),
    ("Maiden Over", "Dot Ball"),
    ("Captain", "Vice Captain"),
    ("Opening Batter", "Finisher"),
    ("All Rounder", "Fast Bowler"),
    ("Off Spin", "Leg Spin"),
    ("Run Out", "Stumping"),
    ("LBW", "Caught Behind"),
    ("Test Mace", "World Cup Trophy"),
    ("Auction", "Mega Auction"),
    ("Toss", "Match Referee"),
    ("Net Run Rate", "Points Table"),
    ("Six", "Four"),
    ("Duck", "Golden Duck"),
    ("Follow On", "Declaration"),
    ("Knockout", "League Stage"),
    ("Qualifier", "Eliminator"),
    ("Pink Ball", "Red Ball"),
    ("Sledging", "Appeal"),
    ("Nightwatchman", "Power Hitter"),
    ("Fielding", "Wicketkeeping"),
    ("Middle Order", "Top Order"),
    ("Slower Ball", "Knuckle Ball"),
    ("Reverse Swing", "Conventional Swing"),
    ("Run Chase", "Target"),
    ("Boundary", "Maximum"),
    ("Spinner", "Pacer"),
    ("Captaincy", "Coaching"),
    ("Strike Rate", "Economy Rate")
]