PLAYER_WORDS = [

    ("Virat Kohli", "AB de Villiers"),
    ("Rohit Sharma", "Shikhar Dhawan"),
    ("MS Dhoni", "Rishabh Pant"),
    ("Sachin Tendulkar", "Brian Lara"),
    ("Chris Gayle", "Andre Russell"),
    ("Hardik Pandya", "Krunal Pandya"),
    ("KL Rahul", "Shubman Gill"),
    ("Babar Azam", "Mohammad Rizwan"),
    ("Jasprit Bumrah", "Mohammed Shami"),
    ("Yuvraj Singh", "Suresh Raina"),
    ("David Warner", "Steve Smith"),
    ("Ben Stokes", "Jos Buttler"),
    ("Kane Williamson", "Ross Taylor"),
    ("Travis Head", "Glenn Maxwell"),
    ("Pat Cummins", "Mitchell Starc"),
    ("Ravindra Jadeja", "Axar Patel"),
    ("Kuldeep Yadav", "Yuzvendra Chahal"),
    ("Ishan Kishan", "Sanju Samson"),
    ("Tilak Varma", "Rinku Singh"),
    ("Suryakumar Yadav", "Tilak Varma"),
    ("Virender Sehwag", "Gautam Gambhir"),
    ("Anil Kumble", "Harbhajan Singh"),
    ("Lasith Malinga", "Dwayne Bravo"),
    ("Kieron Pollard", "Andre Russell"),
    ("Matthew Hayden", "Adam Gilchrist"),
    ("Faf du Plessis", "Quinton de Kock"),
    ("Shane Watson", "Andrew Symonds"),
    ("Muttiah Muralitharan", "Shane Warne"),
    ("Virat Kohli", "Joe Root"),
    ("Rohit Sharma", "David Warner"),
    ("AB de Villiers", "Glenn Maxwell"),
    ("Bumrah", "Rabada"),
    ("R Ashwin", "Nathan Lyon"),
    ("Ruturaj Gaikwad", "Yashasvi Jaiswal"),
    ("Nitish Rana", "Rahul Tripathi"),
    ("Arshdeep Singh", "Avesh Khan"),
    ("Washington Sundar", "Krunal Pandya"),
    ("Deepak Chahar", "Bhuvneshwar Kumar"),
    ("Mohit Sharma", "Harshal Patel"),
    ("Prithvi Shaw", "Shubman Gill"),
    ("Devdutt Padikkal", "Sai Sudharsan"),
    ("Rahul Dravid", "VVS Laxman"),
    ("Zaheer Khan", "Irfan Pathan"),
    ("Dinesh Karthik", "Robin Uthappa"),
    ("Ajinkya Rahane", "Cheteshwar Pujara"),
    ("Brendon McCullum", "Martin Guptill"),
    ("Aiden Markram", "Heinrich Klaasen"),
    ("Rachin Ravindra", "Devon Conway"),
    ("Shaheen Afridi", "Haris Rauf"),
    ("Imam-ul-Haq", "Fakhar Zaman"),
    ("Sunil Narine", "Varun Chakravarthy")
]